export const parties = [
  {
    partyName: "Δημοκρατική Παράταξη",
    partyAbbrGr: "ΔΗΠΑ",
    partyImg: "depa",
    partyElectionName: {
      el: "Δημοκρατική Παράταξη (ΔΗΠΑ)",
      en: "Democratic Alignment (DIPA)",
      tr: "Demokratik Ittifak",
    },
    partyWebsite: "https://depa.cy/",
    europeanGroupName: "Alliance of Liberals and Democrats (ALDE)",
    europeanGroupWebsite: "https://www.reneweuropegroup.eu/",
    partyAbbreviation: "depa",
  },
  {
    partyName: "Δημοκρατικός Συναγερμός",
    partyAbbrGr: "ΔΗΣΥ",
    partyImg: "disy",
    partyElectionName: {
      el: "Δημοκρατικός Συναγερμός (ΔΗΣΥ)",
      en: "Democratic Rally (DISY)",
      tr: "Demokratik Seferberlik (DISY)",
    },
    partyWebsite: "https://disy.org.cy/elections/",
    europeanGroupName: "European People's Party (EPP)",
    europeanGroupWebsite: "https://www.epp.eu/",
    partyAbbreviation: "disy",
  },
  {
    partyName: "Κίνημα Σοσιαλδημοκρατών ΕΔΕΚ",
    partyAbbrGr: "ΕΔΕΚ",
    partyImg: "edek",
    partyElectionName: {
      el: "ΕΔΕΚ Σοσιαλιστικό Κόμμα ",
      en: "EDEK Socialist Party",
      tr: "EDEK Sosyalist Partisi",
    },
    partyWebsite:
      "https://www.edek.org.cy/%CE%95%CE%BA%CE%BB%CE%BF%CE%B3%CE%AD%CF%82",
    europeanGroupName: "Socialists & Democrats (S&D)",
    europeanGroupWebsite: "https://www.socialistsanddemocrats.eu/",
    partyAbbreviation: "edek",
  },
  {
    partyName: "ΕΘνικό Λαϊκό Μέτωπο",
    partyAbbrGr: "ΕΛΑΜ",
    partyImg: "elam",
    partyElectionName: {
      el: "Εθνικό Λαϊκό Μέτωπο (ΕΛΑΜ)",
      en: "National People's Front? (ELAM)",
      tr: "Milli Halk Cephesi (ELAM)",
    },
    partyWebsite: "https://elamcy.com/ypopsifioi-evroekloges-2024/",
    europeanGroupName: "European Conservatives and Reformists (ECR)",
    europeanGroupWebsite: "https://www.ecrgroup.eu/",
    partyAbbreviation: "elam",
  },
  {
    partyName: "Δημοκρατικό Κόμμα",
    partyAbbrGr: "ΔΗΚΟ",
    partyImg: "diko",
    partyElectionName: {
      el: "Δημοκρατικό Κόμμα (ΔΗΚΟ)",
      en: "Democratic Party (DIKO)",
      tr: "Demokratik Parti (DIKO)",
    },
    partyWebsite: "https://democraticparty.org.cy/",
    europeanGroupName: "Socialists & Democrats (S&D)",
    europeanGroupWebsite: "https://www.socialistsanddemocrats.eu/",
    partyAbbreviation: "diko",
  },
  {
    partyName: "Volt Cyprus",
    partyAbbrGr: "Volt",
    partyImg: "volt",
    partyElectionName: {
      el: "VOLT Κύπρος",
      en: "VOLT Cyprus",
      tr: "VOLT Kıbrıs",
    },
    partyWebsite: "https://voltcyprus.org/",
    europeanGroupName: "VOLT Europa",
    europeanGroupWebsite: "https://www.greens-efa.eu/en/",
    partyAbbreviation: "volt",
  },
  {
    partyName: "Ανορθωτικό Κόμμα Εργαζόμενου Λαού",
    partyAbbrGr: "ΑΚΕΛ",
    partyImg: "akelv2",
    partyElectionName: {
      el: "ΑΚΕΛ - Αριστερά - Κοινωνική Συμμαχία",
      en: "AKEL - Left - Social Alliance",
      tr: "AKEL-Sol-Toplumsal İttifak",
    },
    partyWebsite: "https://akel.org.cy/",
    europeanGroupName: "The Left in the European Parliament (GUE/NGL)",
    europeanGroupWebsite: "https://left.eu/",
    partyAbbreviation: "akel",
  },
  {
    partyName: "Κίνημα Οικολόγων Συνεργασία Πολιτών",
    partyAbbrGr: "Οικολόγοι",
    partyImg: "greens",
    partyElectionName: {
      el: "Κίνημα Οικολόγων - Συνεργασία Πολιτών",
      en: "Cyprus Greens - Citiens'Alliance",
      tr: "Kıbrıs Yeşiller Partisi - Vatandaşlar İşbirliği",
    },
    partyWebsite:
      "https://cyprusgreens.org/project_category/euroelections2024/",
    europeanGroupName: "European Greens",
    europeanGroupWebsite: "https://europeangreens.eu/",
    partyAbbreviation: "greens",
  },
];
